packages:
  - 'apps/*'
  - 'packages/*'
# minimumReleaseAge: 10080
minimumReleaseAge: 0
allowBuilds:
  esbuild: true
  lefthook: true
catalogMode: strict
cleanupUnusedCatalogs: true
catalog:
  '@changesets/cli': ^2.31.0
  '@commitlint/cli': ^21.1.0
  '@commitlint/config-conventional': ^21.1.0
  '@commitlint/types': ^21.1.0
  '@types/node': ^26.0.1
  dotenv: ^17.4.2
  lefthook: ^2.1.9
  oxfmt: ^0.57.0
  tsdown: ^0.22.3
  turbo: ^2.10.1
  typescript: ^6.0.3
